version: "~> 1.0"
git:
    depth: 1
    quiet: true
language: java
jdk:
    - openjdk21
branches:
    only:
        - develop
        - support/4.1
cache:
    directories:
        - "$HOME/.m2"
notifications:
    slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
    - mkdir -p $HOME/.m2
    - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
    - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
    global:
        - secure: "tTNaVUyQCeTQ8pUImVj5EZvbiGkzlQWed240S4bW66NEWa5yadss9B7hxy4YIhzOrLdDB706f6mOJxr2dv5TjN6Rrfo9+5OynqSfs4x6DTTHQzmfJLg0+PpogqCzo5fNYQkR9Q4vP3Nou4AMQzW1jQUCm/Nw9VHSru7cYCJmYcE="
        - secure: "AdOdVvK9kLwXqO2qPu7Abn1vO8v7lyQFeiFNk649KUsECQ8QZlHzODwbFCmyFSIK79ROG59xakfz5MqWwLd9j7XYEjE9T25rylWc+tBQBZ7sCdwC0K5ubU14RPVmHAFYXMZZ7AeP7+vEeGf+ihakw2tVkDNuRjnHAs7CtvhNcQc="
